package com.example.coctails.utils

const val COCKTAIL = "COCKTAIL"
const val COCKTAIL_PHOTO = "COCKTAIL_PHOTO"
const val COCKTAIL_NAME = "COCKTAIL_NAME"
const val COCKTAIL_INFO = "COCKTAIL_INFO"

const val CATEGORY = "CATEGORY"
const val TOOLBAR_TITLE = "TOOLBAR_TITLE"
const val CATEGORY_TYPE = "CATEGORY_TYPE"

const val GLASS_ID = "GLASS_ID"

const val INGREDIENT_CATEGORY = "INGREDIENT_CATEGORY"
const val INGREDIENT_INTERFACE = "INGREDIENT_INTERFACE"
const val INGREDIENT_ID = "INGREDIENT_ID"

const val ARG_SECTION_NUMBER = "section_number"

const val CHANGED_FROM_ALL = "CHANGED_FROM_ALL"
const val CHANGED_FROM_INGREDIENT = "CHANGED_FROM_INGREDIENT"

const val FAVORITE_INTERFACE = "FAVORITE_INTERFACE"

const val EQUIPMENT_ID = "EQUIPMENT_ID"
const val GUIDE_ID = "GUIDE_ID"


