package com.example.coctails.utils

const val COCKTAIL = "COCKTAIL"
const val COCKTAIL_PHOTO = "COCKTAIL_PHOTO"
const val COCKTAIL_NAME = "COCKTAIL_NAME"
const val COCKTAIL_INFO = "COCKTAIL_INFO"

const val CATEGORY = "CATEGORY"
const val TOOLBAR_TITLE = "TOOLBAR_TITLE"
const val CATEGORY_TYPE = "CATEGORY_TYPE"

const val GLASS_ID = "GLASS_ID"

const val INGREDIENT_CATEGORY = "INGREDIENT_CATEGORY"
const val INGREDIENT_TYPE= "INGREDIENT_TYPE"
const val INGREDIENT_CATEGORY_NAME= "INGREDIENT_CATEGORY_NAME"
const val INGREDIENT_ID = "INGREDIENT_ID"

const val ARG_SECTION_NUMBER = "section_number"

